# Generated by Django 5.1.3 on 2024-11-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_message_file_alter_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=10),
        ),
    ]
