# Generated by Django 5.1.3 on 2024-11-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_hive_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiveMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=200)),
                ('hive_name', models.CharField(max_length=200)),
            ],
        ),
    ]
