# Generated by Django 5.1.3 on 2024-12-01 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_poll_option_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='vanish_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='vanish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('queen', 'Queen'), ('moderator', 'Moderator'), ('bee', 'Bee')], default='bee', max_length=20)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
